SELECT t2.TABLE_NAME
FROM
(SELECT * FROM TABLES WHERE TABLE_SCHEMA='tableName_temp') AS t2
LEFT JOIN
(SELECT * FROM TABLES WHERE TABLE_SCHEMA='tableName') AS t1
ON t1.TABLE_NAME = t2.TABLE_NAME
WHERE t1.TABLE_NAME IS NULL