SELECT t2.TABLE_NAME, t2.COLUMN_NAME
FROM
(SELECT * FROM COLUMNS WHERE TABLE_SCHEMA='tableName_temp') AS t2
LEFT JOIN
(SELECT * FROM COLUMNS WHERE TABLE_SCHEMA='tableName') AS t1
ON t1.TABLE_NAME = t2.TABLE_NAME AND t1.COLUMN_NAME = t2.COLUMN_NAME
WHERE t1.COLUMN_NAME IS NULL